include:
  - project: rwdt/ci-tools/gitlab-ci-snippets
    file: semver.gitlab-ci.yml

variables:
  REGISTRY_URL: https://${DOCKER_REGISTRY}
  REGISTRY_IMAGE: ${DOCKER_REGISTRY}/${PROJECT_NAME}
  SHORT_SHA_IMAGE: ${REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  LATEST_IMAGE: ${REGISTRY_IMAGE}:latest
  VERSION_IMAGE: ${REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}

#image: docker:dind

default:
  tags:
    - docker

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - push
  - release

before_script:
  - echo -n $TOKEN | docker login -u $DOCKER_USER --password-stdin cr.yandex

docker-build:
  stage: build
  script:
    - docker pull $LATEST_IMAGE || echo "Failed to find latest image in registry"
    - >
      docker build
      --pull
      --cache-from $LATEST_IMAGE
      --tag $SHORT_SHA_IMAGE
      .
    - docker push $SHORT_SHA_IMAGE

docker-push-latest:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - main
    - branches
  script:
    - docker pull $SHORT_SHA_IMAGE
    - docker tag $SHORT_SHA_IMAGE $LATEST_IMAGE
    - docker push $LATEST_IMAGE

docker-push-tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - tags
  script:
    - docker pull $SHORT_SHA_IMAGE
    - docker tag $SHORT_SHA_IMAGE $VERSION_IMAGE
    - docker push $VERSION_IMAGE

release-version:
  extends: .release-version
  rules:
    - when: on_success
