image: docker:latest
services:
  - docker:dind
variables:
  REGISTRY_URL: https://${DOCKER_REGISTRY}
  IMAGE: ${DOCKER_REGISTRY}/${PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}
  RELEASE: ${DOCKER_REGISTRY}/${PROJECT_NAME}:latest
  IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
  
cache:
  paths:
    - node_modules/

stages:
  - builds
    
build:
  stage: builds
  tags:
    - docker
  before_script:
    - apk add --no-cache git # Install Git
    - docker login --username ${DOCKER_USER} --password ${TOKEN} cr.yandex
  script:
    - docker build --pull -t $IMAGE .
    - docker push ${DOCKER_REGISTRY}/${PROJECT_NAME}:${IMAGE_TAG}
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH