version: '3.8'

services:
  postgres:
    container_name: asvi-postgres
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    env_file:
      - ./.env
