export const monitoringDetailMapper = {
  inventoryId: 'ID инвентаризационной описи',
  inventoryCode: 'Код формы описи',
  inventoryNumber: 'Номер описи',
  tabelNumbers: 'Проверяемые табельные номера',
  conferenceId: 'ID конференции',
  username: 'Логин пользователя',
  userStatus: 'Статус пользователя',
  name: 'ФИО пользователя',
  adminDepartment: 'Отдел администратора',
  adminUsername: 'Логин администратора',
  adminName: 'ФИО администратора',
  createdUserUsername: 'Логин созданного пользователя',
  createdUserName: 'ФИО созданного пользователя',
  editedUserUsername: 'Логин редактируемого пользователя',
  editedUserName: 'ФИО редактируемого пользователя',
  addressBefore: 'Адрес до изменений',
  addressAfter: 'Адрес после изменений',
  roleBefore: 'Роль до изменений',
  roleAfter: 'Роль после изменений',
  emailInput: 'Введенный адрес электронной почты',
  loginInput: 'Введенный логин',
  department: 'Отдел',
  error: 'Текст ошибки',
  eventId: 'ID инвентаризации',
  orderId: 'ID приказа',
  orderDate: 'Дата приказа',
  orderNumber: 'Номер приказа',
  ASOZNumber: 'Номер заявки АС ОЗ',
  videoFileName: 'Название видео-файла',
  hashFileName: 'Название hash-файла',
  subtitlesFileName: 'Название файла мета-данных',
  videoFileSize: 'размер видео-файла',
  hashFileSize: 'размер hash-файла',
  editedUserId: 'ID редактируемого пользователя'
  // ------------
  // createdUser: 'Созданный пользователь',
  // editedUser: 'Редактируемый пользователь',
} as const;
